
spring:
  cloud:
    gateway:
      routes:
      - id: service-products
        uri: lb://service-products
        predicates:
          - Path=/api/productss/**
        filters:
          - StripPrefix=2
          - name: Example
            args:
              message: Hello custom message
              cookieName: User
              cookieValue: CarolinaGomez
      - id: service-items
        uri: lb://service-items
        predicates:
          - Path=/api/items/**
        filters:
          - StripPrefix=2